name = input("enter your name : ")
branch = input("enter your branch : ")
college = input("enter your college name : ")
year = input("in which year you studying : ")
age = input("enter your age : ")
print("name : ",name)
print("branch : ",branch)
print("college : ",college)
print("year : ",year)
print("age : ",age)
