p1=int(input("enter the runs of player1 in 60 balls : "))
p2=int(input("enter the runs of player2 in 60 balls : "))
p3=int(input("enter the runs of player3 in 60 balls : "))
print("strike rate of player1 is",p1*100/60)
print("strike rate of player2 is",p2*100/60)
print("strike rate of player2 is",p2*100/60)
print("runs of player1 at 60 more balls",p1*2)
print("runs of player2 at 60 more balls",p2*2)
print("runs of player3 at 60 more balls",p3*2)
print("max hit player1 can make",p1//6)
print("max hit player2 can make",p2//6)
print("max hit player3 can make",p3//6)
